name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"


kv_namespaces = [
  { binding = "NOTES", id = "0939f00fdfe84514ae1f9bf541a8ca6b" },
  { binding = "SHARE", id = "17c1b5ead7f3494e9e12ed85e55d0eb0" }
]
